// AUTO-GENERATED Antigravity writer fixtures — DO NOT EDIT BY HAND.
//
// Antigravity (Google's build of Windsurf/Codeium's "Cascade"/"jetski" engine)
// stores a conversation as a SQLite DB whose payload columns are protobuf. We have
// no .proto to construct those payloads from scratch, so the writer CLONES real
// template blobs captured from a genuine conversation and swaps their ids / text /
// paths via length-prefix-aware protobuf rewriting (see protobuf.ts). These
// fixtures are those template blobs (base64) plus the constants to swap out.
//
// Provenance: a real local Antigravity conversation. The template carried a single
// user turn (step_type 14) and assistant turn (step_type 15); the writer reuses
// those two step shapes for every converted message.

/** Conversation/trajectory schema (all tables + indexes) for a fresh DB. */
export const ANTIGRAVITY_SCHEMA: string[] = [
	"CREATE TABLE `trajectory_meta` (`trajectory_id` text,`cascade_id` text,`trajectory_type` integer,`source` integer,PRIMARY KEY (`trajectory_id`))",
	"CREATE TABLE `steps` (`idx` integer,`step_type` integer NOT NULL DEFAULT 0,`status` integer NOT NULL DEFAULT 0,`has_subtrajectory` numeric NOT NULL DEFAULT false,`metadata` blob,`error_details` blob,`permissions` blob,`task_details` blob,`render_info` blob,`step_payload` blob,`step_format` integer NOT NULL DEFAULT 0,PRIMARY KEY (`idx`))",
	"CREATE TABLE `gen_metadata` (`idx` integer,`data` blob,`size` integer NOT NULL DEFAULT 0,PRIMARY KEY (`idx`))",
	"CREATE TABLE `executor_metadata` (`idx` integer,`data` blob,PRIMARY KEY (`idx`))",
	"CREATE TABLE `parent_references` (`idx` integer,`data` blob,PRIMARY KEY (`idx`))",
	'CREATE TABLE `trajectory_metadata_blob` (`id` text DEFAULT "main",`data` blob,PRIMARY KEY (`id`))',
	"CREATE TABLE `battle_mode_infos` (`idx` integer,`data` blob,PRIMARY KEY (`idx`))",
	"CREATE INDEX `idx_steps_status` ON `steps`(`status`)",
	"CREATE INDEX `idx_steps_step_type` ON `steps`(`step_type`)",
];

/** Identifiers + content baked into the template blobs, swapped out at write time. */
export const TEMPLATE = {
	convId: "f9323256-bc74-4810-8965-5fadbd942f7d",
	trajId: "1ec01e8f-011a-4b4a-8614-f9f3bce751c9",
	turnUuid: "43fe5556-2f73-4dea-be66-f35611e63a75",
	userText: 'How to enable "auto-mode" in agy cli so that all the commands are allowed permission automatically?',
	asstText:
		"I will search the repository to see if there is any mention of `agy`, `auto-mode`, or command execution permissions.",
	/** Source machine paths baked into the blobs (rewritten to the target cwd/home). */
	cwd: "/Users/clawadmin/workspace/codeteleport-monorepo",
	userDir: "/Users/clawadmin",
	trajectoryType: 4,
	source: 17,
	userVersion: 1,
} as const;

/** Step type ids in step_payload field 1 / the steps.step_type column. */
export const STEP_TYPE = { user: 14, assistant: 15 } as const;
/** Step status (3 = DONE). */
export const STEP_STATUS_DONE = 3;

const B64 = {
	userStep:
		"CA4gAyqaAQoMCNLkzdEGEJjhr7ICGARiJDQzZmU1NTU2LTJmNzMtNGRlYS1iZTY2LWYzNTYxMWU2M2E3NaIBTAokMWVjMDFlOGYtMDExYS00YjRhLTg2MTQtZjlmM2JjZTc1MWM5IiRmOTMyMzI1Ni1iYzc0LTQ4MTAtODk2NS01ZmFkYmQ5NDJmN2TSARIKEAgDEgwI0uTN0QYQmOWBswKaAdEGEmNIb3cgdG8gZW5hYmxlICJhdXRvLW1vZGUiIGluIGFneSBjbGkgc28gdGhhdCBhbGwgdGhlIGNvbW1hbmRzIGFyZSBhbGxvd2VkIHBlcm1pc3Npb24gYXV0b21hdGljYWxseT8aZQpjSG93IHRvIGVuYWJsZSAiYXV0by1tb2RlIiBpbiBhZ3kgY2xpIHNvIHRoYXQgYWxsIHRoZSBjb21tYW5kcyBhcmUgYWxsb3dlZCBwZXJtaXNzaW9uIGF1dG9tYXRpY2FsbHk/IgBigAUKxARqngNCBhoCMAF4AIoCAggB0gKNAwoCCAEShgMKggFjb21tYW5kKG5vZGUgL1VzZXJzL2NsYXdhZG1pbi8uZ2VtaW5pL2FudGlncmF2aXR5LWNsaS9icmFpbi8zZWY2NGFlMC1mNmQ0LTQ5OTQtYTUzZC1hYmUwNTZmNmNiNmYvc2NyYXRjaC90ZXN0X3Byb3RvYnVmX3Jld3JpdGUuanMpCmRjb21tYW5kKG5vZGUgL1VzZXJzL2NsYXdhZG1pbi93b3Jrc3BhY2UvY29kZXRlbGVwb3J0LW1vbm9yZXBvL3NjcmlwdHMvZ2VtaW5pLWNoYXQtdGVsZXBvcnQubWpzIGxpc3QpCpgBY29tbWFuZChub2RlIC9Vc2Vycy9jbGF3YWRtaW4vd29ya3NwYWNlL2NvZGV0ZWxlcG9ydC1tb25vcmVwby9zY3JpcHRzL2dlbWluaS1jaGF0LXRlbGVwb3J0Lm1qcyBidW5kbGUgLS1zZXNzaW9uLWlkIDNlZjY0YWUwLWY2ZDQtNDk5NC1hNTNkLWFiZTA1NmY2Y2I2Zil6Awj8B9ICkwF6WgpYEAEaMRovL1VzZXJzL2NsYXdhZG1pbi8uZ2VtaW5pL2FudGlncmF2aXR5LWNsaS9za2lsbHMaIRofL1VzZXJzL2NsYXdhZG1pbi8uZ2VtaW5pL3NraWxsc4gBAVoyCjAvVXNlcnMvY2xhd2FkbWluL3dvcmtzcGFjZS9jb2RldGVsZXBvcnQtbW9ub3JlcG+YAwASAnAAYjdmaWxlOi8vL1VzZXJzL2NsYXdhZG1pbi93b3Jrc3BhY2UvY29kZXRlbGVwb3J0LW1vbm9yZXBv",
	asstStep:
		"CA8gAyrBAgoMCNLkzdEGEIC+xr0CGAIyDAjU5M3RBhCo4c2HAjoMCNTkzdEGEMDG+NkDQgwI1OTN0QYQwMb42QNKTQj8BxCFgwEYmQIwGEIhCglzZXNzaW9uSUQSFC0zNzUwNzYzMDM0MzYyODk1NTc5SK8BUGpaF1UzSXphcks4SnFEQ2p1TVB0ZWVQcUFVWPwHYiQ0M2ZlNTU1Ni0yZjczLTRkZWEtYmU2Ni1mMzU2MTFlNjNhNzVqAwj8B6IBTgokMWVjMDFlOGYtMDExYS00YjRhLTg2MTQtZjlmM2JjZTc1MWM5EAIiJGY5MzIzMjU2LWJjNzQtNDgxMC04OTY1LTVmYWRiZDk0MmY3ZKgBAdIBJAoQCAgSDAjU5M3RBhDQldSHAgoQCAMSDAjU5M3RBhCAhfnZA4ICDAjU5M3RBhDAxvjZA6IB6woKdEkgd2lsbCBzZWFyY2ggdGhlIHJlcG9zaXRvcnkgdG8gc2VlIGlmIHRoZXJlIGlzIGFueSBtZW50aW9uIG9mIGBhZ3lgLCBgYXV0by1tb2RlYCwgb3IgY29tbWFuZCBleGVjdXRpb24gcGVybWlzc2lvbnMuMihib3QtNWZlNDgwZDAtZTE0My00ODNkLWJkYjQtOGY0NGZjZmVlMDFlOtAICghoejUzNWdzNxILZ3JlcF9zZWFyY2ga6wF7IkNhc2VJbnNlbnNpdGl2ZSI6dHJ1ZSwiSXNSZWdleCI6ZmFsc2UsIk1hdGNoUGVyTGluZSI6ZmFsc2UsIlF1ZXJ5IjoiYXV0by1tb2RlIiwiU2VhcmNoUGF0aCI6Ii9Vc2Vycy9jbGF3YWRtaW4vd29ya3NwYWNlL2NvZGV0ZWxlcG9ydC1tb25vcmVwbyIsInRvb2xBY3Rpb24iOiJTZWFyY2hpbmcgZm9yIGF1dG8tbW9kZSBpbiByZXBvc2l0b3J5IiwidG9vbFN1bW1hcnkiOiJTZWFyY2ggZm9yIGF1dG8tbW9kZSJ9OrsGErgGCrUGAQw51segqGSi+c8VPuFn9P6SR2LysE7FmPWoqhyWm7PjZ+QWRjmQC1Hxhn1wPqgXvG/HdBayZuTVn7+2PdlGyRGjRhHpOAp61J8stJOTmDPAEg9vK1ht8v255qIalLSUrl/gwbZ0HLp50plvS6RuSRFIP2wJUFdWfd4Cxg5921gCpJ4+0Vm20/CgsFZDa+G3ad4AHMycuhfV6nj4LnLR+XAE8+rTSLXCEnArqY2wnER5jn64SVhlLUw6Ovbmojm+NuQ3Y4HuH5gjoICBNgK649LPHV0emOpR7PAOZ14v91LjXbJ49YJUdFjBdQV8Z19FD8jzXabCO1HPfqbhY+yWSbzzlRK1isFD0uT1xqhGBXLK63TkKsOHt/R1j8zVXdE/3YODenjIxWYOsilkf148ssSQl+f8xDNfBM6GAzoT9E1VTMoKimYdcU9HEmnZYwUXDHE5FwwzyXFSW6FfC/Vblz9WESAVY6sEuI1U00MjlV7X2W1UwdLiaStglkezSbrkenOvb+UIiIbaVHpyOskVRxMLnP6kpm8maRpzXm563lGqE04vC2w2EM9f+2sQHQBKeKCC7NhNhljoDDSY77EUaYzi/18kOmrto/EF1cInF5T1qjrG15pXLPdZA4hJRgRdSLnAWthImZEfbGu0fuQ5yHemavX5mCTjTi5ZO0Sh3Cm2sZupcBUYV9Q71lmqnCXnRydpDENCfKbQry+7qhw09F0t5YdkrCBRqnakrrSfByMn5MMprH2dEteVoZco8RLzW9hZvfc2GjeMO+dJtMzbvJXTGhneIxtTwkabwdr6M1qZHxjaueBP3nt44k6JPRPYpnr8byJ4IizUWnXFP+wUDPT7DYx6pGA6yMngut1dZc9TWt2zwmqTN9uSAB8tWKKWJ4zVhrN9wUUCe/u+NgtuAWuLhp9deWIKvtPlb2BNFWJ6GRvEwXUYG3VAUY6sVA/73pYrNV7bO+KNZf+exzNH68VNncj0bbDWIqH9WKemJY6qN4SNKJQJVLpUDeCXH9PdE/X9qVpnHqjQQq60EQD16knL72L86kr+6mDdeseJ6VUyRP8mbeoc7MdrlPonuwrAmKGSRgdKC2dyZXBfc2VhcmNoQnRJIHdpbGwgc2VhcmNoIHRoZSByZXBvc2l0b3J5IHRvIHNlZSBpZiB0aGVyZSBpcyBhbnkgbWVudGlvbiBvZiBgYWd5YCwgYGF1dG8tbW9kZWAsIG9yIGNvbW1hbmQgZXhlY3V0aW9uIHBlcm1pc3Npb25zLmAC",
	trajectoryMeta:
		"CsUBCjdmaWxlOi8vL1VzZXJzL2NsYXdhZG1pbi93b3Jrc3BhY2UvY29kZXRlbGVwb3J0LW1vbm9yZXBvEjdmaWxlOi8vL1VzZXJzL2NsYXdhZG1pbi93b3Jrc3BhY2UvY29kZXRlbGVwb3J0LW1vbm9yZXBvGksKGm5hd2Fhei1rb3J2b2wvY29kZXRlbGVwb3J0Ei1naXRAZ2l0aHViLmNvbTpuYXdhYXota29ydm9sL2NvZGV0ZWxlcG9ydC5naXQiBG1haW4SDAjS5M3RBhDw0LipAhokYWEwMzAyMzktYmIxNy00YjE0LWEyMzYtYWQ1MjhiMGNmODg4MiRmOTMyMzI1Ni1iYzc0LTQ4MTAtODk2NS01ZmFkYmQ5NDJmN2Q6N2ZpbGU6Ly8vVXNlcnMvY2xhd2FkbWluL3dvcmtzcGFjZS9jb2RldGVsZXBvcnQtbW9ub3JlcG967AKIn8wyru/LMs/svjLVs8oygtDyMfCQszLykLMy1Pm2Mru9xDLP0b0y1O/VMtDMxjL+/Nwyk7zIMreLvDKoqdMyhJ62Ms2QgjLX7bAylIfIMu33gzKD/7wyxILAMuDUxjKKvcQykIfIMou9xDLi94MyofW6MrPErjKCxbwyzdG9MpPj9DHAgsAy/vPLMo+wvjKJk80y3rjXMuKE1zLo7boy1O2wMqzErjLPos0yuou8Mra9xDL31MYyob3EMvKlzjLNos0yr9nHMrqygzKc0cky++bQMuPUxjL0tdQy6u26MvaxjzGD5dgyntHJMtHsvjL9vMQy8LGPMZSrvzL7z/IxiJy2MN6E1zKt2ccy1dbMMoSTzTKgvcQy7bq/Mt/31jLs1swy7LXUMqXFyTDUwc4yjLbUMs/d1jKm9boy8rrFMsHI/THk1dMygp62MsqQgjK4hscyke/LMtPSuDKlwMsyiYfIMsPsvjK/soMykgEkNmE5YzdmZDUtYThlMC00ZWNkLTg3ODgtNTc2YmU1ZWQ3OWNh",
	executorMeta:
		"CAQQDBgZSiQ0M2ZlNTU1Ni0yZjczLTRkZWEtYmU2Ni1mMzU2MTFlNjNhNzVShhcKgRUI/AcwgIAEOAFqsxES3QMKBi5pcHluYhABIh0NbxKDOhABKgwIARAFGMgBIAUouAIwBEABSABQASqjAwgBEp4DQXMgSURFIGZlZWRiYWNrLCB0aGUgZm9sbG93aW5nIGxpbnQgZXJyb3JzIG1heSBiZSByZWxhdGVkIHRvIHlvdXIgcmVjZW50IGVkaXRzIHVwIHRvIHRoaXMgcG9pbnQuIENvbnNpZGVyIHdoZXRoZXIgdGhleSBkZXNlcnZlIGltbWVkaWF0ZSBhdHRlbnRpb24uIElmIHdvcnRoIGFkZHJlc3NpbmcsIGNsZWFybHkgY29tbWVudCBvbiB0aGVtIGFuZC9vciBmaXggdGhlbS4gQmUgZXhwbGljaXQgaW4gYWNrbm93bGVkZ2luZyBsaW50cyBhbmQgZXhwbGFpbmluZyB5b3VyIGZpeCdzIGFwcHJvYWNoLiBBVk9JRCB1bnByb2R1Y3RpdmUgbG9vcHM7IGlmIHlvdSBkZXRlY3QgeW91cnNlbGYgcmVwZWF0ZWRseSBjcmVhdGluZy9maXhpbmcgbGludHMgaW4gYSBzaG9ydCBwZXJpb2QsIG9mZmVyIHNvbWUgdGhvdWdodHMgYnV0IE1PVkUgT04uMABQAGgAeACAAQCQAQAaBwi4AhDAuAIiBggyOABAACoICDIYACAAKAFCawiAQBAAGk4wAUoEaGVhZEoEdGFpbEoFbWtkaXJKAmNkSgJjcEoCbXZKA2NhdEoEZmluZEoEZ3JlcEoCcm1KBXRvdWNoSgRsZXNzSgVjbGVhckoCbHMgACoDenNoMgN6c2hYAGAAaABwAHgAUhk4AEABSIBAUIBAWIAEaAFwoAZ4AZABgOgCWgIIAWoGCAASAggCggEFCAAQgCCaAQC6ARIIARCAQBiACCCsAigFMAE4ygLKAX0IABoCCAEiJAgEEPoHGAEoADICCgA43I4EQgUIARCQTkoCCAFaBAgBEAFgASoXChUqA3JlZDj/AUAASABQ/wFYGWABaAIwAzgAUgQIARAAaAF6AggBkgECCAGaAQIIAaABAKgBALABALgBAMABAMgBANABAdgBAOABAOgBAPoBAhgAggIFCAoQiCeKAgIIAaICALICAggAugIICAEgCigAMAHKAgIIAdICwwoKAggBEoYDCoIBY29tbWFuZChub2RlIC9Vc2Vycy9jbGF3YWRtaW4vLmdlbWluaS9hbnRpZ3Jhdml0eS1jbGkvYnJhaW4vM2VmNjRhZTAtZjZkNC00OTk0LWE1M2QtYWJlMDU2ZjZjYjZmL3NjcmF0Y2gvdGVzdF9wcm90b2J1Zl9yZXdyaXRlLmpzKQpkY29tbWFuZChub2RlIC9Vc2Vycy9jbGF3YWRtaW4vd29ya3NwYWNlL2NvZGV0ZWxlcG9ydC1tb25vcmVwby9zY3JpcHRzL2dlbWluaS1jaGF0LXRlbGVwb3J0Lm1qcyBsaXN0KQqYAWNvbW1hbmQobm9kZSAvVXNlcnMvY2xhd2FkbWluL3dvcmtzcGFjZS9jb2RldGVsZXBvcnQtbW9ub3JlcG8vc2NyaXB0cy9nZW1pbmktY2hhdC10ZWxlcG9ydC5tanMgYnVuZGxlIC0tc2Vzc2lvbi1pZCAzZWY2NGFlMC1mNmQ0LTQ5OTQtYTUzZC1hYmUwNTZmNmNiNmYpIrMHCgZweXRob24KB3B5dGhvbjMKB3B5dGhvbjIKBG5vZGUKBHJ1YnkKBHBlcmwKA2x1YQoDcGhwCgRiYXNoCgJzaAoDenNoCgRmaXNoCgNjc2gKBHRjc2gKA2tzaAoEZGFzaAoDYXNoCgZzb3VyY2UKBGV2YWwKBGV4ZWMKAnJtCgVybWRpcgoFc2hyZWQKBHN1ZG8KAnN1CgRkb2FzCgRjdXJsCgR3Z2V0CgNzc2gKA3NjcAoFcnN5bmMKAm5jCgRuY2F0CgNwaXAKBHBpcDMKBHBpcHgKBWNhcmdvCgJnbwoCZGQKBG1rZnMKBWZkaXNrCgVtb3VudAoGdW1vdW50CgVjaG93bgoFY2htb2QKBmNocm9vdAoEa2lsbAoHa2lsbGFsbAoGcmVib290CgRoYWx0EgNnaXQSAmhnEgJnNBICamoSA3N2bhIFYmxhemUSBWJhemVsEgRtYWtlEgVuaW5qYRIGZ3JhZGxlEgNtdm4SBGJ1Y2sSBWJ1Y2syEgVwYW50cxIFc2NvbnMSBWNtYWtlEgVtZXNvbhIEanVzdBIFZm9yZ2USBWdsYXplEglidWlsZG96ZXISA25wbRIEeWFybhIEcG5wbRIDYnVuEgRicmV3EgNhcHQSB2FwdC1nZXQSA2RuZhIGcGFjbWFuEgZkb2NrZXISBnBvZG1hbhIHa3ViZWN0bBIGZ2Nsb3VkEgZnc3V0aWwSAmJxEghmaXJlYmFzZRICYXoSA2F3cxIIZmlsZXV0aWwSDWJ1aWxkX2NsZWFuZXISBnN0dWJieRIFcmFwaWQSBm1lbmRlbBIGZ3VpdGFyEgNib3ESA2djbBIGZjEtc3FsEgVibHV6ZRIJcnBjcmVwbGF5EgRmbGV4EglzeXN0ZW1jdGwSCmpvdXJuYWxjdGwSCWxhdW5jaGN0bBo6CglzeXN0ZW1jdGwSLQoHcmVzdGFydAoEc3RvcAoFc3RhcnQKBmVuYWJsZQoHZGlzYWJsZQoEbWFzaxodCglsYXVuY2hjdGwSEAoGdW5sb2FkCgZyZW1vdmUaGwoDZ2l0EhQKBHB1c2gKBWNsZWFuCgVyZXNldBobCgRicmV3EhMKCXVuaW5zdGFsbAoGcmVtb3ZlGikKB2t1YmVjdGwSHgoGZGVsZXRlCgVkcmFpbgoGY29yZG9uCgV0YWludBoeCgZkb2NrZXISFAoDcnVuCgRleGVjCgJybQoDcm1pGh4KBnBvZG1hbhIUCgNydW4KBGV4ZWMKAnJtCgNybWnYAgDiAgIIAfACAIIDAggBkAMAegMI/AeqAQoIACACKgIBAkAB4gEUZ2VtaW5pLTMuNS1mbGFzaC1sb3fyASEKBAgEGAESGQgCEOgHGQAAAAAAAABAIAEpmpmZmZmZ2T+CAhcIABD6BxjAmgwgFCiQTjAUOBRAZEjoB4gCAKgCANICkwF6WgpYEAEaMRovL1VzZXJzL2NsYXdhZG1pbi8uZ2VtaW5pL2FudGlncmF2aXR5LWNsaS9za2lsbHMaIRofL1VzZXJzL2NsYXdhZG1pbi8uZ2VtaW5pL3NraWxsc4gBAVoyCjAvVXNlcnMvY2xhd2FkbWluL3dvcmtzcGFjZS9jb2RldGVsZXBvcnQtbW9ub3JlcG/aAqkBChoKFGpldHNraS1nZW5lcmF0aXZlLXVpEgIIAAogChplbmFibGUtbGVhcm4tc2xhc2gtY29tbWFuZBICCAEKHgoYZW5hYmxlLW93bC1zbGFzaC1jb21tYW5kEgIIAAoeChhlbmFibGUtc3RhdGUtYWNjdW11bGF0b3ISAggACikKI2Rpc2FibGUtdGVhbXdvcmstZm9yY2VkLWZsYXNoLW1vZGVsEgIIAPgCAZIDBBAAIACYAwASAnAAElgIoI0GEAEdmpkZPiABKIDQDzABOJoIWICAAWgBchkIABDoBxkAAAAAAAAAQCAAKZqZmZmZmdk/eAGAAQqIAYAIkAEUmAEBuAEByAEB0AEB2AEB4AEA6AEBGigIABD///////////8BKAEwCkAASABYAWAAaAF4AYABAIgBAJIBAggAIigoADIQCAEQABgAIIAgKIAQMAA4ADgBQAFIAFABWABgAGiAgAFwAHgAOg8IARAUGGQg6Aco6Acw0A9AAUoCCAFaAggAYjdmaWxlOi8vL1VzZXJzL2NsYXdhZG1pbi93b3Jrc3BhY2UvY29kZXRlbGVwb3J0LW1vbm9yZXBvWuwC+8/yMZSrvzLstdQy49TGMoq9xDKlxckwgsW8MvCxjzGsxK4yiYfIMrqLvDKJk80y99TGMqb1ujKLvcQyypCCMvvm0DLQzMYyv7KDMs2QgjLEgsAy4NTGMpPj9DG6soMynNHJMtWzyjLU+bYyzdG9Mq7vyzLypc4y09K4MoictjDP7L4y/vzcMtTBzjKe0ckypcDLMvKQszL+88syk7zIMs/RvTKC0PIx3rjXMuTV0zL9vMQywILAMq3ZxzKPsL4yoL3EMu33gzKMttQykIfIMt/31jLR7L4y1O2wMriGxzLwkLMyz93WMreLvDK7vcQywcj9MertujLehNcy9LXUMoPl2DLtur8y1+2wMtTv1TKhvcQyofW6MsPsvjKEk80y4veDMqip0zLyusUy9rGPMYP/vDLs1swy6O26MtXWzDLPos0yhJ62MoKetjLNos0ytr3EMrPErjKUh8gyke/LMoifzDLihNcyr9nHMg==",
};

/** Template protobuf blobs, decoded to Buffers. */
export const TEMPLATE_BLOBS = {
	/** A step_type 14 (user input) step_payload. */
	userStep: Buffer.from(B64.userStep, "base64"),
	/** A step_type 15 (assistant/planner response) step_payload. */
	asstStep: Buffer.from(B64.asstStep, "base64"),
	/** The trajectory_metadata_blob "main" row (workspace cwd, git, ids). */
	trajectoryMeta: Buffer.from(B64.trajectoryMeta, "base64"),
	/** The executor_metadata row. */
	executorMeta: Buffer.from(B64.executorMeta, "base64"),
};
